version: '3.6'

services:
#  worker:
#    image: node:20.11.0-alpine
#    container_name: sp-worker
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    networks:
#      - sp

  mongodb:
    image: mongo:4.2.3-bionic
    container_name: sp-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=kpm
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./db_data:/data/db
      - ./db_config:/data/configdb
    networks:
      - sp

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - sp

volumes:
  mongoconfig:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  sp:
    driver: bridge
