# fly.toml app configuration file generated for shopee-tool on 2023-12-21T10:39:37+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopee-tool"
primary_region = "sin"
release_command = "node src/app.js"
[build]

[http_service]
  internal_port = 3000
  force_https = true
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
